/**
 * Comment Service API
 * Comment management operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageableObject } from './pageableObject';
import { CommentResponse } from './commentResponse';
import { SortObject } from './sortObject';


export interface PageCommentResponse { 
    totalElements?: number;
    totalPages?: number;
    size?: number;
    content?: Array<CommentResponse>;
    number?: number;
    sort?: SortObject;
    first?: boolean;
    last?: boolean;
    numberOfElements?: number;
    pageable?: PageableObject;
    empty?: boolean;
}

