/**
 * Game Resource Service API
 * Game Resource management operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValueUnitDto } from './valueUnitDto';
import { ResResponse } from './resResponse';


export interface BuildingResponse extends ResResponse { 
    size?: string;
    decorRadius?: number;
    decorEffect?: number;
    thermalConductivity?: number;
    storageCapacity?: ValueUnitDto;
    power?: ValueUnitDto;
    heat?: ValueUnitDto;
    overheatTemp?: ValueUnitDto;
    recipes?: { [key: string]: any; } | null;
}
export namespace BuildingResponse {
}


