/**
 * Game Resource Service API
 * Game Resource management operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValueUnitDto } from './valueUnitDto';
import { ResResponse } from './resResponse';
import { RangeValueDto } from './rangeValueDto';


export interface CritterResponse extends ResResponse { 
    livableRange?: RangeValueDto;
    decorRadius?: number;
    decorEffect?: number;
    caloriesNeeded?: ValueUnitDto;
    hp?: number;
    spaceRequired?: number;
    layEggEvery?: ValueUnitDto;
    dropsOnDeath?: number;
    glum?: boolean;
    wild?: boolean;
}
export namespace CritterResponse {
}


