/**
 * Game Resource Service API
 * Game Resource management operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResResponse } from './resResponse';


export interface ElementResponse extends ResResponse { 
    thermalConductivity?: number;
    specificHeatCapacity?: number;
    molarMass?: number;
    hardness?: number;
    lightAbsorptionFactor?: number;
    state?: ElementResponse.StateEnum;
    stateTransition?: { [key: string]: any; } | null;
    recipes?: { [key: string]: any; } | null;
}
export namespace ElementResponse {
    export type StateEnum = 'SOLID' | 'LIQUID' | 'GAS';
    export const StateEnum = {
        Solid: 'SOLID' as StateEnum,
        Liquid: 'LIQUID' as StateEnum,
        Gas: 'GAS' as StateEnum
    };
}


