/**
 * Game Resource Service API
 * Game Resource management operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValueUnitDto } from './valueUnitDto';
import { ResResponse } from './resResponse';
import { RangeValueDto } from './rangeValueDto';


export interface GeyserResponse extends ResResponse { 
    maxPressure?: ValueUnitDto;
    avgEmissionRate?: RangeValueDto;
    totalEruptionPeriod?: RangeValueDto;
    activeOfEruptionPeriod?: RangeValueDto;
    totalPeriod?: RangeValueDto;
    activePeriod?: RangeValueDto;
}
export namespace GeyserResponse {
}


