/**
 * Game Resource Service API
 * Game Resource management operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecipeDto } from './recipeDto';
import { ValueUnitDto } from './valueUnitDto';
import { ResResponse } from './resResponse';


export interface MedicineResponse extends ResResponse { 
    duration?: ValueUnitDto;
    radiationRecovery?: number;
    germResistance?: number;
    disease?: number;
    recipe?: RecipeDto;
}
export namespace MedicineResponse {
}


