/**
 * Game Resource Service API
 * Game Resource management operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResResponse } from './resResponse';
import { RangeValueDto } from './rangeValueDto';


export interface PathogenResponse extends ResResponse { 
    temperature?: RangeValueDto;
    canCause?: number;
    droppedBy?: Array<number>;
    disinfectedBy?: Array<number>;
}
export namespace PathogenResponse {
}


