/**
 * Game Resource Service API
 * Game Resource management operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResResponse } from './resResponse';
import { RangeValueDto } from './rangeValueDto';


export interface PlantResponse extends ResResponse { 
    airPressure?: RangeValueDto;
    temp?: RangeValueDto;
    baseDecor?: number;
}
export namespace PlantResponse {
}


