/**
 * Game Resource Service API
 * Game Resource management operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResSimpleResponse { 
    id?: number;
    name?: string;
    description?: string;
    imageUrl?: string;
    resType?: ResSimpleResponse.ResTypeEnum;
}
export namespace ResSimpleResponse {
    export type ResTypeEnum = 'ELEMENT' | 'BUILDING' | 'CRITTER' | 'EGG' | 'PLANT' | 'SEED' | 'FOOD' | 'PLANET' | 'ARTIFACT' | 'COMET' | 'GEYSER' | 'MEDICINE' | 'DISEASE' | 'PATHOGEN' | 'MISC';
    export const ResTypeEnum = {
        Element: 'ELEMENT' as ResTypeEnum,
        Building: 'BUILDING' as ResTypeEnum,
        Critter: 'CRITTER' as ResTypeEnum,
        Egg: 'EGG' as ResTypeEnum,
        Plant: 'PLANT' as ResTypeEnum,
        Seed: 'SEED' as ResTypeEnum,
        Food: 'FOOD' as ResTypeEnum,
        Planet: 'PLANET' as ResTypeEnum,
        Artifact: 'ARTIFACT' as ResTypeEnum,
        Comet: 'COMET' as ResTypeEnum,
        Geyser: 'GEYSER' as ResTypeEnum,
        Medicine: 'MEDICINE' as ResTypeEnum,
        Disease: 'DISEASE' as ResTypeEnum,
        Pathogen: 'PATHOGEN' as ResTypeEnum,
        Misc: 'MISC' as ResTypeEnum
    };
}


