/**
 * Game Resource Service API
 * Game Resource management operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecipeDto } from './recipeDto';
import { PlantResponse } from './plantResponse';
import { GeyserResponse } from './geyserResponse';
import { MedicineResponse } from './medicineResponse';
import { OtherResponse } from './otherResponse';
import { SeedResponse } from './seedResponse';
import { EggResponse } from './eggResponse';
import { BuildingResponse } from './buildingResponse';
import { PlanetResponse } from './planetResponse';
import { RangeValueDto } from './rangeValueDto';
import { CometResponse } from './cometResponse';
import { DiseaseResponse } from './diseaseResponse';
import { ArtifactResponse } from './artifactResponse';
import { PathogenResponse } from './pathogenResponse';
import { ValueUnitDto } from './valueUnitDto';
import { CritterResponse } from './critterResponse';
import { ElementResponse } from './elementResponse';
import { FoodResponse } from './foodResponse';


/**
 * @type TestGet200Response
 * @export
 */
export type TestGet200Response = ArtifactResponse | BuildingResponse | CometResponse | CritterResponse | DiseaseResponse | EggResponse | ElementResponse | FoodResponse | GeyserResponse | MedicineResponse | OtherResponse | PathogenResponse | PlanetResponse | PlantResponse | SeedResponse;

