/**
 * User Service API
 * User management operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserResponse { 
    id?: number;
    username?: string;
    role?: UserResponse.RoleEnum;
    createdAt?: string;
}
export namespace UserResponse {
    export type RoleEnum = 'USER' | 'MODERATOR' | 'ADMIN';
    export const RoleEnum = {
        User: 'USER' as RoleEnum,
        Moderator: 'MODERATOR' as RoleEnum,
        Admin: 'ADMIN' as RoleEnum
    };
}


