/**
 * Image Service API
 * Image management operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ImageResponse { 
    id?: number;
    filename?: string;
    type?: string;
    size?: number;
    storagePath?: string;
    ownerId?: number;
    createdAt?: string;
}

