/**
 * Tag Service API
 * Tag management operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TagRequest { 
    name: string;
    type?: TagRequest.TypeEnum;
}
export namespace TagRequest {
    export type TypeEnum = 'DLC' | 'BUILD';
    export const TypeEnum = {
        Dlc: 'DLC' as TypeEnum,
        Build: 'BUILD' as TypeEnum
    };
}


