/**
 * Build Service API
 * Build management operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BuildRequest { 
    name: string;
    description: string;
    tagId?: Array<number>;
}

