/**
 * Build Service API
 * Build management operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageableObject } from './pageableObject';
import { BuildResponse } from './buildResponse';
import { SortObject } from './sortObject';


export interface PageBuildResponse { 
    totalPages?: number;
    totalElements?: number;
    size?: number;
    content?: Array<BuildResponse>;
    number?: number;
    sort?: SortObject;
    first?: boolean;
    last?: boolean;
    numberOfElements?: number;
    pageable?: PageableObject;
    empty?: boolean;
}

